test-job: # 임의로 지정한 JOB 이름
  stage: deploy # build, test, deploy 3단계 스테이지 중 하나
  only:
    - fe/develop # develop 브랜치 이벤트 발생시 실행
  script:
    - echo "Hello World" # 실행할 스크립트
    - git pull origin fe/develop
    - cd /client
    - next kill
    - npm install
    - npm run build
    - pm2 start npm --name "next" -w -i max -- start
    - npm run start
  tags:
    - nextjs # build-server 태그가 달린 runner에서 실행
