test-job: # 임의로 지정한 JOB 이름
  stage: deploy # build, test, deploy 3단계 스테이지 중 하나
  only:
    - fe/develop # develop 브랜치 이벤트 발생시 실행
  script:
    - echo "Hello World" # 실행할 스크립트
    # /home/gitlab-runner/builds/sZ_Zkzi3/0/s08-bigdata-recom-sub2/S08P22D203
    - git pull origin fe/develop
    # - pm2 stop next
    # - pm2 kill
    - cd client
    - echo 'ubuntu' | sudo -S npm i -g
    - npm run build
    - pm2 start npm --name "next" -w -i max -- start
    - npm run start
  tags:
    - nextjs # build-server 태그가 달린 runner에서 실행
